<?php

/**
 * implements hook_init().
 */
function drupalcon_general_init() {
  $path = $_GET['q'];
  if ($path == 'other-trips') {
    //TODO find something better
    sleep(10);
  }
}

/**
 * Implements hook_menu().
 */

function drupalcon_general_menu() {

  $items['admin/config/development/drupalcon'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupalcon_config_form'),
    'access arguments' => array('access devel information'),
    'title' => 'Drupalcon Config',
    'description' => 'Configure aspects of the Drupalcon Website'
  );

  return $items;
}

function drupalcon_config_form($form, $form_state) {
  $form = array();

  $form['drupalcon_debug_active'] = array(
    '#title' => t('Debug mode for drupalcon active'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('drupalcon_debug_active')
  );

  return system_settings_form($form);
}