<?php

/**
 * implements hook_init().
 */
function drupalcon_general_init() {
  $path = $_GET['q'];

  // current drupalcon is closed and path is other-cons
  if ($path = 'other-cons' && variable_get('drupalcon_closed', TRUE)) {
    // wait for 0.2 seconds
    usleep(200000);
  }
}

/**
 * implements hook_block_info().
 */
function drupalcon_general_block_info() {

  $blocks['drupalcon_weather'] = array(
    'info' => t('Drupalcon Weather'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * implements hook_block_info().
 */
function drupalcon_general_block_view($delta) {

  switch ($delta) {
    case 'drupalcon_weather':
      $block['subject'] = t('Weather');
      $block['content'] = drupalcon_show_weather();
      break;
  }

  return $block;
}


/**
 * Implements hook_menu().
 */

function drupalcon_general_menu() {

  $items['admin/config/development/drupalcon'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupalcon_config_form'),
    'access arguments' => array('access devel information'),
    'title' => 'Drupalcon Config',
    'description' => 'Configure aspects of the Drupalcon Website'
  );

  $items['user/%user/commits'] = array(
    'page callback' => 'drupalcon_user_commits',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'title' => 'Drupal commits',
    'description' => 'Drupal commits',
    'type' => MENU_LOCAL_TASK
  );
  
  return $items;
}

function drupalcon_user_commits($user) {
  // our data is in an external database 
  
  $bad_query = "select SQL_NO_CACHE * from drupal_external_data.commits
                 left outer join drupal_external_data.modules on modules.module = commits.module
                 left outer join drupal_external_data.users on users.user = commits.maintainer
                 left outer join drupal_external_data.users u2 on u2.user = commits.maintainer
                 left outer join drupal_external_data.users u3 on u3.user = commits.maintainer
                 left outer join drupal_external_data.users u4 on u4.user = commits.maintainer
                 left outer join drupal_external_data.users u5 on u5.user = commits.maintainer
                 where commits.maintainer = :user and commits.module is not NULL
                 order by commits.date";
  
  $good_query = "select SQL_NO_CACHE * from commits USE INDEX (maintainer)
                 inner join modules  on modules.module = commits.module
                 inner join users on users.user = commits.maintainer
                 where commits.maintainer = 'demo'
                 order by commits.date
                 limit 0,100";

 
  if ($user->uid == 1) {
    $user_query = $good_query;
  }
  else {
    $user_query = $bad_query;
  }

  $i = 0;
  $rows = array();
  $results = db_query($user_query, array(':user' => $user->name), array('target' => 'drupal_external_data'));
  foreach($results as $res) {
    // just 100 first rows
    if ($i < 100) {
      $rows[] = array($res->maintainer, $res->module, format_date($res->date));
    }
    $i++;  
  }

  $header = array( 
    array('data' => t('User')),  
    // second cell 
    array('data' => t('Module')), 
    // and third cell 
    array('data' => t('Date'))); 

  $content = theme('table', array('header' => $header, 'rows' => $rows));

  return $content;
}

function drupalcon_config_form($form, $form_state) {
  $form = array();

  $form['drupalcon_debug_active'] = array(
    '#title' => t('Debug mode for drupalcon active'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('drupalcon_debug_active')
  );

  $form['drupalcon_closed'] = array(
    '#title' => t('Drupalcon closed'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('drupalcon_closed', TRUE)
  );

  return system_settings_form($form);
}


function drupalcon_show_weather() {

  timer_start('drupalcon_weather');
  // wait for 0.2 seconds
  usleep(200000);
  $node = node_load(arg(1));
  $block['subject'] = t('Current weather nearby');
  $block['content'] = '';
  $display = weather_get_display_settings('default', 1);

  if (!empty($node)) {
    $locations = field_get_items('node', $node, 'field_location');
    $location = $locations[0];
  }

  // default locations
  if (empty($location['latitude']) or (empty($location['longitude']))) {
    $location['latitude'] = '50.5';
    $location['longitude'] = '14.26';
  }

  $station = weather_get_nearest_station($location['latitude'], $location['longitude']);
  $metar = weather_get_metar($station->icao);

  $timer = timer_read('drupalcon_weather');

  if (variable_get('drupalcon_debug_active', FALSE)) {
    drupal_set_message ('time spent with drupalcon weather - ' . $timer);
  }

  return theme('weather_theming',   array('display' => $display, 'location' => $station, 'metar' => $metar));
}
